DROP DATABASE IF EXISTS employee_db;

CREATE DATABASE employee_db;
USE employee_db;


CREATE TABLE Department(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(30)
);

CREATE TABLE Job(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(30) NOT NULL,
    salary DECIMAL UNSIGNED,
    department_id INT UNSIGNED,
    FOREIGN KEY (department_id) REFERENCES Department(id)
);

CREATE TABLE Employee(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(30) NOT NULL,
  last_name VARCHAR(30) NOT NULL,
  role_id INT UNSIGNED,
  manager_id INT UNSIGNED NULL,
  FOREIGN KEY (role_id) REFERENCES Job(id),
  FOREIGN KEY (manager_id) REFERENCES Employee(id)
);
